import React from 'react';
import { AdventureTheme } from './types';
import { WandStarIcon, EyeIcon, BoltIcon, CompassIcon, GhostIcon, HeartIcon, TargetIcon, SwordIcon, ShieldIcon, CyberEyeIcon, NinjaIcon, BrainIcon } from './components/icons';

export const initialAdventures: AdventureTheme[] = [
    { id: 'a1', title: 'Epic Fantasy', description: 'Embark on magical quests with dragons, wizards, and ancient mysteries.', keywords: 'Mystical realms, powerful magic, heroic quests', icon: React.createElement(WandStarIcon), imageUrl: 'https://picsum.photos/seed/fantasy/600/400' },
    { id: 'a2', title: 'Thrilling Mystery', description: 'Solve chilling puzzles and uncover dark secrets in atmospheric settings.', keywords: 'Detective work, hidden clues, psychological suspense', icon: React.createElement(EyeIcon), imageUrl: 'https://picsum.photos/seed/mystery/600/400' },
    { id: 'a3', title: 'Space Odyssey', description: 'Explore distant galaxies and encounter alien civilizations beyond imagination.', keywords: 'Future tech, space exploration, alien encounters', icon: React.createElement(BoltIcon), imageUrl: 'https://picsum.photos/seed/space/600/400' },
    { id: 'a4', title: 'Jungle Adventure', description: 'Discover hidden treasures and ancient secrets in exotic locations.', keywords: 'Exploration, treasure hunting, survival challenges', icon: React.createElement(CompassIcon), imageUrl: 'https://picsum.photos/seed/jungle/600/400' },
    { id: 'a5', title: 'Spine-Chilling Horror', description: 'Face your darkest fears in haunting tales of supernatural terror.', keywords: 'Supernatural threats, survival horror, psychological dread', icon: React.createElement(GhostIcon), imageUrl: 'https://picsum.photos/seed/horror/600/400' },
    { id: 'a6', title: 'Passionate Romance', description: 'Navigate the complexities of love in heartwarming and dramatic tales.', keywords: 'Love stories, emotional connections, dramatic twists', icon: React.createElement(HeartIcon), imageUrl: 'https://picsum.photos/seed/romance/600/400' },
    { id: 'a7', title: 'Wild West', description: 'Ride into frontier towns and face outlaws in the untamed American West.', keywords: 'Cowboys, saloons, duels, frontier justice', icon: React.createElement(TargetIcon), imageUrl: 'https://picsum.photos/seed/west/600/400' },
    { id: 'a8', title: 'Martial Arts Master', description: 'Master ancient fighting techniques and seek honor in epic martial arts battles.', keywords: 'Martial arts, honor codes, ancient masters', icon: React.createElement(SwordIcon), imageUrl: 'https://picsum.photos/seed/martialarts/600/400' },
    { id: 'a9', title: 'Superhero Adventures', description: 'Discover extraordinary powers and protect the innocent from evil villains.', keywords: 'Superpowers, heroic missions, saving the world', icon: React.createElement(ShieldIcon), imageUrl: 'https://picsum.photos/seed/superhero/600/400' },
    { id: 'a10', title: 'Cyber Detective', description: 'Solve futuristic crimes with advanced technology in cyberpunk cities.', keywords: 'Cyber investigations, future tech, dystopian society', icon: React.createElement(CyberEyeIcon), imageUrl: 'https://picsum.photos/seed/cyber/600/400' },
    { id: 'a11', title: 'Shadow Operative', description: 'Master high-tech stealth missions as an elite cyber-ninja spy.', keywords: 'Stealth, cyber espionage, ninja tactics', icon: React.createElement(NinjaIcon), imageUrl: 'https://picsum.photos/seed/ninja/600/400' },
    { id: 'a12', title: 'Psychological Terror', description: 'Experience intense psychological suspense and terrifying mind games.', keywords: 'Psychological horror, intense suspense, unreliable narrator', icon: React.createElement(BrainIcon), imageUrl: 'https://picsum.photos/seed/psychological/600/400' },
];